name: autofix.ci

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  autofix:
    if: "!startsWith(github.event.pull_request.title, 'renovate/')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --frozen-lockfile
      - run: pnpm run fmt
      - run: pnpm run lint:fix

      - uses: autofix-ci/action@7a166d7532b277f34e16238930461bf77f9d7ed8
